// build info - autogenerated do not manually edit
//
//
#ifndef BUILD_INFO_H_
#define BUILD_INFO_H_

//
// Build number
//

// Provide an incremental integer build number//
#define __BI__BUILD_NUMBER 0
#define __BI__BUILD_NUMBER_STR "DEV-0"

//
// Build date & time stamp for 2023:10:31 12:34:42
//

// Provide an integer representation of the time in human-readable form
#define __BI__TIMESTAMP_INT 123442

// Provide a 3 8-bit representation of the time in human-readable form
#define __BI__TIMESTAMP_INT8_HR 12
#define __BI__TIMESTAMP_INT8_MI 34
#define __BI__TIMESTAMP_INT8_SE 42

// Provide a 6 byte string representation of the time
#define __BI__TIMESTAMP_STR "123442"


// Provide an integer representation of the date in human-readable form
#define __BI__DATESTAMP_INT 231031

// Provide a 3 8-bit representation of the date in human-readable form
#define __BI__DATESTAMP_INT8_YR 23
#define __BI__DATESTAMP_INT8_MO 10
#define __BI__DATESTAMP_INT8_DA 31

// Provide a 6 byte string representation of the date
#define __BI__DATESTAMP_STR "231031"

#define __BI__DATEANDTIMESTAMP_STR "231031-123442"
#endif /* BUILD_INFO_H_ */

